# Generated by Django 4.1.1 on 2023-03-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('prize_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prize_type', to='prize_type.prizetype')),
            ],
        ),
    ]
