# Generated by Django 4.1.1 on 2023-03-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prize', '0001_initial'),
        ('period_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('is_special', models.BooleanField(default=False)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('period_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='period_type.periodtype')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='prize.prize')),
            ],
        ),
    ]
