# Generated by Django 4.1.1 on 2023-03-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('province', '0001_initial'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='district.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='province.province')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='village.village')),
            ],
        ),
    ]
